- name: Workstation configuration via ansible pull
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Load host vars from host_vars/{{ ansible_hostname }}.yml
      include_vars:
        file: "inventory/host_vars/{{ ansible_hostname }}.yml"
    - name: Print host name
      debug:
        var: ansible_hostname
    - name: Print group affiliation
      debug:
        msg: "{{ ansible_group | join(', ') }}"
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes
  
  tasks:
    - name: Run individual plays
      loop: "{{ ansible_group }}"
      include_tasks: "group_{{ group }}.yml"
      loop_control:
        loop_var: group
      