- name: Workstation configuration via ansible pull
  hosts: localhost
  connection: local
  become: yes

  pre_tasks:
    - name: Load host vars from host_vars/{{ ansible_hostname }}.yml
      include_vars:
        file: "host_vars/{{ ansible_hostname }}.yml"
    - name: Print host name
      debug:
        var: ansible_hostname
    - name: Print group affiliation
      debug:
        msg: "{{ ansible_group | join(', ') }}"
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes

  tasks:
    - name: Print the value of new_var
      debug:
        var: new_var