- name: Ensure i3wm and related packages are installed
  apt:
    name:
      - i3
      - feh
      - rofi
      - polybar
      - picom
      - redshift
    state: present

- name: i3wm configuration
  include_tasks: i3wm.yml

- name: rofi menu configuration
  include_tasks: rofi.yml

- name: polybar configuration
  include_tasks: polybar.yml